---
title: "PSTAT194CS_SNA_Final_Project"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,   # hides code
  message = FALSE,
  warning = FALSE
)
```

# Dataset

# Loading and Preparing Data
```{r}
url = "https://snap.stanford.edu/data/web-Google.txt.gz"
download.file(url, destfile = "web-Google.txt.gz", mode = "wb")
```
```{r}
library(igraph)

edges = read.table(
  "web-Google.txt.gz",
  comment.char = "#",
)

graph = graph_from_data_frame(edges, directed=TRUE)
```

# Understanding our Network
```{r}
cat("Number of Nodes:",vcount(graph),"\n")
cat("Number of Edges:",ecount(graph))
```

```{r}
is_directed(graph)
```



```{r}
is_weighted(graph)
```


```{r}
summary(graph)
```






# Creating Subgraphs of 200-nodes



## Code Implemenation
```{r}
set.seed(123)

sub.network = lapply(1:4, function(x){
  induced_subgraph(graph, sample(V(graph),200))
})
```

## Checking Subgraphs
```{r}
sub.network[[1]]
sub.network[[2]]
sub.network[[3]]
sub.network[[4]]
```










## New Implementation
```{r}
set.seed(123)

subgraphs <- list()

for(i in 1:4){

  repeat{

    seed <- sample(V(graph), 1)

    neighbors_nodes <- ego(graph, order = 2, nodes = seed, mode = "all")[[1]]

    if(length(neighbors_nodes) >= 200) break
  }

  sample_nodes <- sample(neighbors_nodes, 200)

  subgraphs[[i]] <- induced_subgraph(graph, sample_nodes)
}


```

## Checking our Subgraphs
```{r}
subgraphs[[1]]
subgraphs[[2]]
subgraphs[[3]]
subgraphs[[4]]
```


# Visualization 

```{r}
layouts = list(layout_with_fr, layout_with_kk, layout_in_circle)

for(i in 1:4){
  for (j in 1:3){
    plot(
      subgraphs[[i]],
      layout = layouts[[j]],
      vertex.size = 4,
      vertex.label = NA,
      edge.arrow.size = 0.2,
      main= paste("Subgrah", i,"- Layout", j)
    )
  }
}
```









































\newpage

## Appendix

```{r appendix-code, ref.label=knitr::all_labels(), echo=TRUE, eval=FALSE}
```
